// themes.ets

// 定义多个换肤主题
export const themeColor1: Array<[number, number]> = [
  [0xFFD700, 0],   // 金黄色
  [0x1E90FF, 1.0]  // 道奇蓝色
];

export const themeColor2: Array<[number, number]> = [
  [0x2F4F4F, 0],   // 深海绿色
  [0x4682B4, 1.0]   // 钢蓝色
];

export const themeColor3: Array<[number, number]> = [
  [0x3CB371, 0],    // 中海绿色
  [0x228B22, 1.0]   // 森林绿色
];

export const themeColor4: Array<[number, number]> = [
  [0x8B008B, 0],    // 暗紫色
  [0x4B0082, 1.0]   // 靛蓝色
];

export const themeColor5: Array<[number, number]> = [
  [0x556B2F, 0],    // 橄榄深绿
  [0x808000, 1.0]   // 橄榄色
];

export const themeColor6: Array<[number, number]> = [
  [0xC71585, 0],    // 深粉色
  [0x800080, 1.0]   // 紫色
];

export const themeColor7: Array<[number, number]> = [
  [0x008B8B, 0],    // 暗青色
  [0x5F9EA0, 1.0]   // 深灰蓝色
];

export const themeColor8: Array<[number, number]> = [
  [0xFF6347, 0],    // 番茄红
  [0x8B0000, 1.0]   // 深红色
];

export const themeColor9: Array<[number, number]> = [
  [0x9932CC, 0],    // 深紫色
  [0x8A2BE2, 1.0]   // 紫罗兰色
];

export const themeColor10: Array<[number, number]> = [
  [0xD2691E, 0],    // 巧克力色
  [0xB22222, 1.0]   // 火砖红
];

export const themeColor11: Array<[number, number]> = [
  [0x2F4F4F, 0],    // 深海绿色
  [0x4B0082, 1.0]   // 靛蓝色
];

export const themeColor12: Array<[number, number]> = [
  [0x8B4513, 0],    // 深橙色
  [0x2F4F4F, 1.0]   // 深海绿色
];

export const themeColor13: Array<[number, number]> = [
  [0x2E8B57, 0],    // 海洋绿
  [0x006400, 1.0]   // 深绿色
];
